export const paymentData = [
  {
    name: "Neha",
    mode: "cash",
    method: "full",
    id: 1,
    course: "FrontEnd",
  },
  {
    name: "Muskan",
    mode: "online",
    method: "EMI",
    id: 2,
    course: "BackEnd",
  },
  {
    name: "Palvi",
    mode: "other",
    method: "full",
    id: 3,
    course: "Mobile App",
  },
  {
    name: "Gunjan",
    mode: "cash",
    method: "full",
    id: 4,
    course: "Marketing",
  },
  {
    name: "Anjali",
    mode: "online",
    method: "EMI",
    id: 5,
    course: "Managemwnt",
  },
  {
    name: "Preeti",
    mode: "other",
    method: "EMI",
    id: 6,
    course: "Designning",
  },
  {
    name: "Shakshi",
    mode: "cash",
    method: "full",
    id: 7,
    course: "FrontEnd",
  },
  {
    name: "Pankaj",
    mode: "online",
    method: "EMI",
    id: 8,
    course: "BackEnd",
  },
  {
    name: "Ishu",
    mode: "online",
    method: "EMI",
    id: 9,
    course: "Mobile App",
  },
  {
    name: "Keshav",
    mode: "cash",
    method: "full",
    id: 10,
    course: "Marketing",
  },
  {
    name: "Rahul",
    mode: "online",
    method: "full",
    id: 11,
    course: "Designing",
  },
  {
    name: "Surender",
    mode: "cash",
    method: "EMI",
    id: 12,
    course: "Management",
  },
  {
    name: "Kunal",
    mode: "other",
    method: "EMI",
    id: 13,
    course: "FrontEnd",
  },
  {
    name: "Sachin",
    mode: "online",
    method: "EMI",
    id: 14,
    course: "BackEnd",
  },
  {
    name: "Mohit",
    mode: "cash",
    method: "full",
    id: 15,
    course: "MobileApp",
  },
  {
    name: "Shubham",
    mode: "other",
    method: "full",
    id: 16,
    course: "Designning",
  },
  {
    name: "Sumit",
    mode: "cash",
    method: "EMI",
    id: 17,
    course: "Management",
  },
  {
    name: "Naveen",
    mode: "online",
    method: "full",
    id: 18,
    course: "Marketing",
  },
  {
    name: "Jyoti",
    mode: "cash",
    method: "EMI",
    id: 19,
    course: "FrontEnd",
  },
  {
    name: "Kumkum",
    mode: "other",
    method: "full",
    id: 20,
    course: "BackEnd",
  },
  {
    name: "Roshni",
    mode: "cash",
    method: "full",
    id: 21,
    course: "Mobile App",
  },
  {
    name: "Rakesh",
    mode: "online",
    method: "EMI",
    id: 22,
    course: "Designing",
  },
  {
    name: "Puneet",
    mode: "other",
    method: "full",
    id: 23,
    course: "Marketing",
  },
  {
    name: "Keshav",
    mode: "cash",
    method: "full",
    id: 24,
    course: "Management",
  },
  {
    name: "Manoj",
    mode: "online",
    method: "EMI",
    id: 25,
    course: "FrontEnd",
  },
  {
    name: "Vikram",
    mode: "other",
    method: "EMI",
    id: 26,
    course: "BackEnd",
  },

  {
    name: "Vikas",
    mode: "online",
    method: "EMI",
    id: 27,
    course: "MobileApp",
  },
  {
    name: "Indu",
    mode: "online",
    method: "EMI",
    id: 28,
    course: "Designing",
  },
  {
    name: "Pooja",
    mode: "cash",
    method: "full",
    id: 29,
    course: "Marketing",
  },
  {
    name: "Sonali",
    mode: "online",
    method: "full",
    id: 30,
    course: "Management",
  },
  {
    name: "Vijay",
    mode: "cash",
    method: "EMI",
    id: 31,
    course: "FrontEnd",
  },
  {
    name: "Mahi",
    mode: "other",
    method: "EMI",
    id: 32,
    course: "BackEnd",
  },
  {
    name: "Ansh",
    mode: "online",
    method: "EMI",
    id: 33,
    course: "Management",
  },
  {
    name: "Alka",
    mode: "cash",
    method: "full",
    id: 34,
    course: "Marketing",
  },
  {
    name: "Sagar",
    mode: "other",
    method: "full",
    id: 35,
    course: "Mobile App",
  },
  {
    name: "Kuldeep",
    mode: "cash",
    method: "EMI",
    id: 36,
    course: "FrontEnd",
  },
  {
    name: "Madeep",
    mode: "online",
    method: "full",
    id: 37,
    course: "Backend",
  },
  {
    name: "Diksha",
    mode: "cash",
    method: "EMI",
    id: 38,
    course: "Designing",
  },
  {
    name: "Jaspal",
    mode: "other",
    method: "full",
    id: 39,
    course: "Wordpress",
  },
  {
    name: "Neha",
    mode: "cash",
    method: "full",
    id: 40,
    course: "Webflow",
  },
  {
    name: "Muskan",
    mode: "online",
    method: "EMI",
    id: 41,
    course: "FrontEnd",
  },
  {
    name: "Palvi",
    mode: "other",
    method: "full",
    id: 42,
    course: "Mobile App",
  },
  {
    name: "Gunjan",
    mode: "cash",
    method: "full",
    id: 43,
    course: "Backend",
  },
  {
    name: "Anjali",
    mode: "online",
    method: "EMI",
    id: 44,
    course: "Designing",
  },
  {
    name: "Preeti",
    mode: "other",
    method: "EMI",
    id: 45,
    course: "Wordpress",
  },
  {
    name: "Shakshi",
    mode: "cash",
    method: "full",
    id: 46,
    course: "Webflow",
  },
  {
    name: "Pankaj",
    mode: "online",
    method: "EMI",
    id: 47,
    course: "FrontEnd",
  },
  {
    name: "Ishu",
    mode: "online",
    method: "EMI",
    id: 48,
    course: "Backend",
  },
  {
    name: "Keshav",
    mode: "cash",
    method: "full",
    id: 49,
    course: "Marketing",
  },
  {
    name: "Rahul",
    mode: "online",
    method: "full",
    id: 50,
    course: "Management",
  },
];

export const data = [
  {
    title: "Demon Deck",
    createdAt: "9-26-2022",
    dueOn: "9-27-2022",
    isCompleted: true,
    isNew: false,
    id: 1,
  },
  {
    title: "BS",
    createdAt: "9-24-2022",
    dueOn: "9-27-2022",
    isCompleted: false,
    isNew: false,
    id: 2,
  },
  {
    title: "Slinky Winky",
    createdAt: "9-28-2022",
    dueOn: "9-26-2022",
    isCompleted: true,
    isNew: true,
    id: 3,
  },
  {
    title: "Demon yellow sasdsad",
    createdAt: "10-5-2022",
    dueOn: "10-5-2022",
    isCompleted: false,
    isNew: false,
    id: 4,
  },
  {
    title: "Demon yellow",
    createdAt: "10-4-2022",
    dueOn: "10-6-2022",
    isCompleted: false,
    isNew: true,
    id: 5,
  },

  {
    title: "ABC",
    createdAt: "9-25-2022",
    dueOn: "9-28-2022",
    isCompleted: false,
    isNew: true,
    id: 6,
  },
  {
    title: "ABC",
    createdAt: "9-24-2022",
    dueOn: "9-30-2022",
    isCompleted: false,
    isNew: false,
    id: 7,
  },
  {
    title: "BSnew",
    createdAt: "9-24-2022",
    dueOn: "10-3-2022",
    isCompleted: true,
    isNew: false,
    id: 8,
  },
  {
    title: "Slinky Winky full",
    createdAt: "9-24-2022",
    dueOn: "10-2-2022",
    isCompleted: true,
    isNew: false,
    id: 9,
  },
  {
    title: "XYZ",
    createdAt: "9-24-2022",
    dueOn: "10-6-2022",
    isCompleted: false,
    isNew: true,
    id: 10,
  },
];
